#!/bin/bash
echo "📝 Instructions pour créer le repository GitHub:"
echo ""
echo "1. Allez sur: https://github.com/new"
echo "2. Repository name: Nemesis-Launcher"
echo "3. Description: Launcher Minecraft officiel Nemesis avec support Fabric 1.21.1"
echo "4. Public ou Private: à votre choix"
echo "5. NE PAS ajouter README, .gitignore ou license (déjà présents localement)"
echo "6. Cliquez sur 'Create repository'"
echo ""
echo "Puis lancez ces commandes:"
echo "cd ~/github/Minecraft/nemesis-launcher"
echo "git remote set-url origin https://github.com/EspritFurifX/Nemesis-Launcher.git"
echo "git push -u origin master"
